### PR TITLE
Ror

### PR DESCRIPTION
**Pull request by bennyng**
Dockferized RoR PetStore

### CODE REVIEW

**Comment by vincentserpoul** [comment]
still not building on my side

`
Step 4/11 : ADD Gemfile* /app/
ADD failed: no source files were specified
`

**Comment by bennyng** [comment]
I did a fresh clone from `bennyng:ror` but cannot repeat the issue
what do see from folder ruby-no rails?

**Comment by vincentserpoul** [comment]
can you rebase from master?

**Comment by vincentserpoul** [comment]
I need the api to listen to: http://0.0.0.0:8080/pet/1 instead of http://0.0.0.0:8080/api/pets/1
I tried a few things, but it doesn't seem to work
i you have any idea :P @bennyng

**Comment by bennyng** [comment]
@vincentserpoul yes, [PR#4](https://github.com/vincentserpoul/kubench/pull/4) ready ;)

**Pull request merged**
